project:
  type: website
  output-dir: docs

website:
  title: "Kyle Suelflow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project Highlights
        menu:
          - text: Data Science
            href: data_visualizations.qmd
          - text: CS OR Other
            href: other_highlights.qmd
    right:
      - icon: envelope
        href: "mailto:ksuelflo@macalester.edu"
        text: Email
      - text: Linkedin
        icon: linkedin
        href: "https://www.linkedin.com/in/kyle-suelflow"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



